[global]
disable = ["MD013"]

[per-file-ignores]
"charts/**/README.md" = ["MD004"]
"**/_description.md" = ["MD041"]

[MD024]
siblings-only = true

[MD033]
allowed-elements = ["br"]

[MD052]
shortcut-syntax = true
