apiVersion: v2
name: confluence-server
description: Helm chart for Atlassian Confluence Server.
type: application
version: 5.5.3
appVersion: 8.5.3
home: https://www.atlassian.com/software/confluence
icon: https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/f6/1f/d8/f61fd8a9-5451-cd1a-8ef0-5b865999bacb/source/256x256bb.jpg
keywords:
  - confluence
  - confluence-server
  - atlassian
  - agile
  - documentation
  - wiki
sources:
  - https://bitbucket.org/atlassian-docker/docker-atlassian-confluence-server
  - https://hub.docker.com/r/atlassian/confluence-server
  - https://github.com/stevehipwell/helm-charts/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
dependencies:
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
annotations:
  artifacthub.io/alternativeName: confluence
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated the _Confluence Server_ OCI image to [v8.5.3](https://confluence.atlassian.com/doc/confluence-8-5-release-notes-1252010185.html)."
    - kind: changed
      description: "Updated the embedded _PostgreSQL_ chart to [v12.12.10](https://artifacthub.io/packages/helm/bitnami/postgresql/12.12.10) (PostgreSQL v15.4.0)."
    - kind: fixed
      description: "Fixed incorrect _PostgreSQL_ sub chart template names."
