apiVersion: v1
name: confluence-server
version: 3.4.0
appVersion: 7.10.0
description: Helm chart for Atlassian Confluence Server.
keywords:
  - confluence
  - confluence-server
  - atlassian
  - agile
  - documentation
  - wiki
home: https://www.atlassian.com/software/confluence
icon: https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/f6/1f/d8/f61fd8a9-5451-cd1a-8ef0-5b865999bacb/source/256x256bb.jpg
sources:
  - https://bitbucket.org/atlassian-docker/docker-atlassian-confluence-server
  - https://hub.docker.com/r/atlassian/confluence-server
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
