apiVersion: v2
name: fluent-bit-aggregator
description: Helm chart for Fluent Bit running as an aggregation stateful set.
type: application
version: 0.16.6
appVersion: 3.2.6
keywords:
  - fluent
  - fluentd
  - fluent bit
  - logging
  - aggregator
home: https://fluentbit.io/
icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/fluent-bit-aggregator/icon.png
sources:
  - https://github.com/fluent/fluent-bit/
  - https://github.com/stevehipwell/helm-charts/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
    url: https://github.com/stevehipwell
annotations:
  artifacthub.io/alternativeName: fluent-bit
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated _Fluent Bit_ OCI image to [v3.2.6](https://github.com/fluent/fluent-bit/releases/tag/v3.2.6)."
