apiVersion: v2
name: node-config
description: Helm chart for configuring Kubernetes nodes via a DaemonSet init container.
type: application
version: 0.5.0
appVersion: 0.1.0
home: https://github.com/stevehipwell/helm-charts/
icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/node-config/icon.png
keywords:
  - node
  - configuration
sources:
  - https://github.com/stevehipwell/helm-charts/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added `affinity.nodeAffinity`."
