apiVersion: v2
name: tigera-operator
description: Helm chart to install the Tigera Operator for managing Calico.
type: application
version: 2.11.5
appVersion: 1.36.5
keywords:
  - kubernetes
  - cni
  - calico
  - tigera
  - operator
  - network
  - policy
  - plugin
home: https://www.tigera.io/
icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/tigera-operator/icon.png
sources:
  - https://github.com/tigera/operator
  - https://github.com/projectcalico/calico
  - https://github.com/stevehipwell/helm-charts/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
annotations:
  artifacthub.io/alternativeName: tigera
