apiVersion: v2
name: istio-operator
description: Helm chart for the Istio Operator.
type: application
version: 2.1.2
appVersion: 1.9.1
keywords:
  - kubernetes
  - istio
  - operator
  - service
  - mesh
home: https://istio.io/
icon: https://istio.io/latest/favicons/android-192x192.png
sources:
  - https://github.com/istio/istio/tree/master/operator
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
annotations:
  artifacthub.io/changes: |
    - Lease istio-operator permission update
