apiVersion: v1
name: istio-operator
version: 1.0.9
appVersion: 1.6.7
description: Helm chart for the Istio Operator.
keywords:
- kubernetes
- istio
- operator
- service
- mesh
home: https://istio.io/
icon: https://istio.io/favicons/android-192x192.png
sources:
- https://github.com/istio/istio
maintainers:
- name: Steve Hipwell
  email: steve.hipwell@gmail.com
