apiVersion: v2
name: istio-operator
description: Helm chart to install the Istio Operator and optionally create the IstioOperator CR to install Istio into the cluster.
type: application
version: 2.14.0
appVersion: 1.21.0
keywords:
  - kubernetes
  - istio
  - operator
  - service
  - mesh
home: https://istio.io/
icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/istio-operator/icon.png
sources:
  - https://github.com/istio/istio/tree/master/operator
  - https://github.com/stevehipwell/helm-charts/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
annotations:
  artifacthub.io/alternativeName: istio
  artifacthub.io/crds: |
    - kind: IstioOperator
      version: v1alpha1
      name: istiooperators.install.istio.io
      displayName: IstioOperator
      description: Represents an installation of Istio to be managed by the Istio Operator.
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated the _Istio Operator_ OCI image version to [v1.21.0](https://github.com/istio/istio/releases/tag/1.21.0)."
    - kind: changed
      description: "Updated dashboards to match upstream."
