apiVersion: v2
name: jira-software
description: Helm chart for Atlassian Jira Software.
type: application
version: 4.2.0
appVersion: 8.16.0
keywords:
  - jira
  - jira-software
  - atlassian
  - agile
  - project
  - management
home: https://www.atlassian.com/software/jira
icon: https://wac-cdn.atlassian.com/dam/jcr:b544631f-b225-441b-9e05-57b7fd0d495b/Jira%20Software@2x-icon-blue.png
sources:
  - https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
  - https://hub.docker.com/r/atlassian/jira-software/
  - https://github.com/stevehipwell/helm-charts/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
dependencies:
  - name: postgresql
    version: ~10.3.17
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - Default to JDK 11 image
    - Upgraded PostgreSQL chart to v10.3.17 (PostgreSQL v11.11.0)
