apiVersion: v2
name: jira-software
description: Helm chart for Atlassian Jira Software.
type: application
version: 5.12.5
appVersion: 9.12.5
keywords:
  - jira
  - jira-software
  - atlassian
  - agile
  - project
  - management
home: https://www.atlassian.com/software/jira
icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/jira-software/icon.png
sources:
  - https://bitbucket.org/atlassian-docker/docker-atlassian-jira/
  - https://hub.docker.com/r/atlassian/jira-software/
  - https://github.com/stevehipwell/helm-charts/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
dependencies:
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
annotations:
  artifacthub.io/alternativeName: jira
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated the _Jira Software_ OCI image to [v9.12.5](https://confluence.atlassian.com/jirasoftware/issues-resolved-in-9-12-0-1318887015.html)."
