apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sonarqube.configName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
data:
  sonar.properties: |
    sonar.es.bootstrap.checks.disable=true
  {{- range $key, $val := .Values.sonarProperties }}
    {{ $key }}={{ $val }}
  {{- end }}
