{{- if .Values.receive.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.receive.router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.receive.router.labels" . | nindent 4 }}
spec:
  {{- if not .Values.receive.router.autoscaling.enabled }}
  replicas: {{ .Values.receive.router.replicas }}
  {{- end }}
  {{- with .Values.receive.router.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "thanos.receive.router.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thanos.receive.router.selectorLabels" . | nindent 8 }}
      {{- with .Values.receive.router.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receive.router.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.receive.router.serviceAccount.automountToken }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "thanos.receive.router.serviceAccountName" . }}
      {{- with .Values.receive.router.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receive.router.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.receive.router.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        - name: thanos-receive-router
          {{- with .Values.receive.router.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "thanos.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOST_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          {{- with .Values.receive.router.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - receive
            - {{ printf "--log.level=%s" .Values.logLevel }}
            - {{ printf "--log.format=%s" .Values.logFormat }}
            - {{ printf "--grpc-address=0.0.0.0:%d" (int .Values.receive.router.grpcPort) }}
            - {{ printf "--http-address=0.0.0.0:%d" (int .Values.receive.router.httpPort) }}
            - {{ printf "--remote-write.address=0.0.0.0:%d" (int .Values.receive.router.httpRemoteWritePort) }}
          {{- if .Values.autoGomemlimit.enabled }}
            - --enable-auto-gomemlimit
          {{- with .Values.autoGomemlimit.ratio }}
            - {{ printf "--auto-gomemlimit.ratio=%s" . }}
          {{- end }}
          {{- end }}
            - --receive.hashrings-file=/etc/thanos/hashrings.json
            - --receive.replication-factor={{ .Values.receive.replicationFactor }}
            - --label=receive_replica="$(NAME)"
          {{- with .Values.receive.router.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: grpc
              protocol: TCP
              containerPort: {{ .Values.receive.router.grpcPort }}
            - name: http
              protocol: TCP
              containerPort: {{ .Values.receive.router.httpPort }}
            - name: http-rem-write
              protocol: TCP
              containerPort: {{ .Values.receive.router.httpRemoteWritePort }}
          livenessProbe:
            {{- toYaml .Values.receive.router.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.receive.router.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: hashrings-config
              mountPath: /etc/thanos/hashrings.json
              subPath: hashrings.json
              readOnly: true
          {{- with .Values.receive.router.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.receive.router.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: hashrings-config
          configMap:
            name: {{ include "thanos.receive.router.hashringsConfigmapName" . }}
      {{- with .Values.receive.router.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receive.router.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receive.router.affinity }}
      {{- $_ := include "thanos.receive.router.patchAffinity" $ }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receive.router.topologySpreadConstraints }}
      {{- $_ := include "thanos.receive.router.patchTopologySpreadConstraints" $ }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receive.router.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
