{{- if .Values.receive.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.receive.router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.receive.router.labels" . | nindent 4 }}
  {{- with .Values.receive.router.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.receive.router.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.receive.router.service.grpcPort }}
      targetPort: grpc
    - name: http
      protocol: TCP
      port: {{ .Values.receive.router.service.httpPort }}
      targetPort: http
    - name: http-rem-write
      protocol: TCP
      port: {{ .Values.receive.router.service.httpRemoteWritePort }}
      targetPort: http-rem-write
  selector:
    {{- include "thanos.receive.router.selectorLabels" . | nindent 4 }}
{{- end -}}
