apiVersion: v2
name: overprovisioner
description: Helm chart for overprovisioning Kubernetes clusters.
type: application
version: 0.4.0
appVersion: 0.4.0
home: https://github.com/stevehipwell/helm-charts/
icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/overprovisioner/icon.png
keywords:
  - cluster
  - scheduler
  - provisioning
  - overprovisioning
  - preemption
sources:
  - https://github.com/stevehipwell/helm-charts/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Changed `capacity.resources` to be object map to support multiple resource types."
