apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vertical-pod-autoscaler.updater.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.updater.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.updater.replicas }}
  {{- with .Values.updater.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.updater.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vertical-pod-autoscaler.updater.selectorLabels" . | nindent 8 }}
      {{- with .Values.updater.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.updater.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName:  {{ include "vertical-pod-autoscaler.updater.serviceAccountName" . }}
      {{- with .Values.updater.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.updater.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.updater.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        - name: updater
          {{- with .Values.updater.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "vertical-pod-autoscaler.updater.image" . }}
          imagePullPolicy: {{ .Values.updater.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- with .Values.updater.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - {{ printf "--v=%s" (toString .Values.logLevel) }}
            - --address=:8943
          {{- with .Values.updater.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http-metrics
              protocol: TCP
              containerPort: 8943
          livenessProbe:
            {{- toYaml .Values.updater.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.updater.readinessProbe | nindent 12 }}
          {{- with .Values.updater.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.updater.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.updater.affinity }}
      {{- $_ := include "vertical-pod-autoscaler.updater.patchAffinity" $ }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.updater.topologySpreadConstraints }}
      {{- $_ := include "vertical-pod-autoscaler.updater.patchTopologySpreadConstraints" $ }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.updater.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
