{{- if .Values.storeGateway.sharded.enabled }}
{{- range $index, $shard := .Values.storeGateway.sharded.timePartitioning }}
{{- $shardName := $shard.name | default (printf "%d" $index) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "thanos.storeGateway.fullname" $) }}-{{ $shardName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "thanos.storeGateway.labels" $ | nindent 4 }}
    shard: {{ $shardName | quote }}
  {{- with $.Values.storeGateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
{{- if (semverCompare ">= 1.31-0" $.Capabilities.KubeVersion.Version) }}
{{- with $.Values.storeGateway.service.trafficDistribution }}
  trafficDistribution: {{ . }}
{{- end }}
{{- end }}
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
    - name: http
      protocol: TCP
      port: 10902
      targetPort: http
  selector:
    {{- include "thanos.storeGateway.selectorLabels" $ | nindent 4 }}
    shard: {{ $shardName | quote }}
{{- end }}
{{- end }}