{{- if .Values.receive.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "thanos.receive.ingestor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.receive.ingestor.labels" . | nindent 4 }}
spec:
  serviceName: {{ printf "%s-headless" (include "thanos.receive.ingestor.fullname" .) }}
  replicas: {{ .Values.receive.ingestor.replicas }}
  {{- with .Values.receive.ingestor.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "thanos.receive.ingestor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thanos.receive.ingestor.selectorLabels" . | nindent 8 }}
      {{- with .Values.receive.ingestor.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.objstoreConfig.create (gt (len .Values.receive.ingestor.podAnnotations) 0) }}
      annotations:
      {{- if .Values.objstoreConfig.create }}
        checksum/config: {{ include "thanos.objstoreConfigHash" . }}
      {{- end }}
      {{- with .Values.receive.ingestor.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "thanos.receive.ingestor.serviceAccountName" . }}
      {{- with .Values.receive.ingestor.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receive.ingestor.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.receive.ingestor.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        - name: thanos-receive-ingestor
          {{- with .Values.receive.ingestor.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "thanos.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOST_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          {{- with .Values.receive.ingestor.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - receive
            - --log.level={{ .Values.logLevel }}
            - --log.format={{ .Values.logFormat }}
            - --grpc-address=0.0.0.0:{{ .Values.grpcPort }}
            - --http-address=0.0.0.0:{{ .Values.httpPort }}
            - --remote-write.address=0.0.0.0:{{ .Values.httpRemoteWritePort }}
            - --objstore.config-file=/etc/thanos/objstore.yaml
          {{- if .Values.autoGomemlimit.enabled }}
            - --enable-auto-gomemlimit
          {{- with .Values.autoGomemlimit.ratio }}
            - --auto-gomemlimit.ratio={{ . }}
          {{- end }}
          {{- end }}
            - --tsdb.path=/var/thanos/receive
            - --tsdb.retention={{ .Values.receive.retention }}
            - --label=receive_replica="$(NAME)"
            - {{ printf "--receive.local-endpoint=$(NAME).%s.%s-headless.svc.%s:%s" (include "thanos.receive.ingestor.fullname" .) .Release.Namespace .Values.clusterDomain .Values.grpcPort }}
          {{- with .Values.receive.ingestor.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: grpc
              protocol: TCP
              containerPort: {{ .Values.grpcPort }}
            - name: http
              protocol: TCP
              containerPort: {{ .Values.httpPort }}
            - name: http-rem-write
              protocol: TCP
              containerPort: {{ .Values.httpRemoteWritePort }}
          livenessProbe:
            {{- toYaml .Values.receive.ingestor.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.receive.ingestor.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: objstore-config
              mountPath: /etc/thanos/objstore.yaml
              subPath: {{ .Values.objstoreConfig.key }}
              readOnly: true
            - name: data
              mountPath: /var/thanos/receive
              readOnly: false
          {{- with .Values.receive.ingestor.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.receive.ingestor.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: objstore-config
          secret:
            secretName: {{ include "thanos.objstoreConfigSecretName" . }}
      {{- if not .Values.receive.ingestor.persistence.enabled }}
        - name: data
          emptyDir: {}
      {{- end }}
      {{- with .Values.receive.ingestor.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receive.ingestor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receive.ingestor.affinity }}
      {{- $_ := include "thanos.receive.ingestor.patchAffinity" $ }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receive.ingestor.topologySpreadConstraints }}
      {{- $_ := include "thanos.receive.ingestor.patchTopologySpreadConstraints" $ }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receive.ingestor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.receive.ingestor.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "thanos.receive.ingestor.selectorLabels" . | nindent 10 }}
        {{- with .Values.receive.ingestor.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
      {{- with .Values.receive.ingestor.persistence.storageClass }}
      {{- if (eq "-" .) }}
        storageClassName: ""
      {{- else }}
        storageClassName: {{ . }}
      {{- end }}
      {{- end }}
        accessModes:
          - {{ .Values.receive.ingestor.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.receive.ingestor.persistence.size }}
  {{- if semverCompare ">= 1.27-0" .Capabilities.KubeVersion.Version }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ ternary "Retain" "Delete" .Values.receive.ingestor.persistence.retainDeleted }}
    whenScaled: {{ ternary "Retain" "Delete" .Values.receive.ingestor.persistence.retainScaled }}
  {{- end }}
  {{- end }}
{{- end -}}
