apiVersion: v2
name: fluentd-aggregator
description: Helm chart for Fluentd running as an aggregation StatefulSet and using the fluent-plugin-route router.
type: application
version: 5.1.0
appVersion: 3.1.0
keywords:
  - fluent
  - fluentd
  - logging
  - aggregator
home: https://www.fluentd.org/
icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/fluentd-aggregator/icon.png
sources:
  - https://github.com/stevehipwell/fluentd-aggregator
  - https://hub.docker.com/r/stevehipwell/fluentd-aggregator
  - https://github.com/stevehipwell/helm-charts/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
annotations:
  artifacthub.io/alternativeName: fluentd
