apiVersion: v2
name: fluentd-aggregator
description: Helm chart for Fluentd running as an aggregation stateful set.
type: application
version: 2.6.2
appVersion: 1.14.1
keywords:
  - fluent
  - fluentd
  - logging
home: https://www.fluentd.org/
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
sources:
  - https://github.com/stevehipwell/fluentd-aggregator
  - https://hub.docker.com/r/stevehipwell/fluentd-aggregator
  - https://github.com/stevehipwell/helm-charts/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Bump version."
