apiVersion: v2
name: plantuml
description: Helm chart for PlantUML Server, a web application to generate UML diagrams on-the-fly.
type: application
version: 3.37.0
appVersion: 1.2025.2
home: https://plantuml.com/
icon: https://raw.githubusercontent.com/stevehipwell/helm-charts/main/charts/plantuml/icon.png
keywords:
  - plantuml
  - diagram
  - uml
  - sequence
sources:
  - https://github.com/plantuml/plantuml-server/
  - https://github.com/stevehipwell/helm-charts/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
annotations: {}
