apiVersion: v2
name: plantuml
description: Helm chart for PlantUML.
type: application
version: 2.8.1
appVersion: 1.2021.7
home: https://plantuml.com/
icon: https://kieranborsden.gallerycdn.vsassets.io/extensions/kieranborsden/plantumllanguageservice/1.1.5.1/1556620084743/Microsoft.VisualStudio.Services.Icons.Default
keywords:
  - plantuml
  - diagram
  - uml
  - sequence
sources:
  - https://github.com/plantuml/plantuml-server/
  - https://github.com/stevehipwell/helm-charts/
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
annotations:
  artifacthub.io/changes: |
    - Support K8s v1.18 ingress changes
    - Remove customisable ingress paths
