apiVersion: v1
name: plantuml
version: 1.1.0
appVersion: 1.2020.18
description: Helm chart for PlantUML.
keywords:
  - plantuml
  - diagram
  - uml
  - sequence
home: https://plantuml.com/
icon: https://kieranborsden.gallerycdn.vsassets.io/extensions/kieranborsden/plantumllanguageservice/1.1.5.1/1556620084743/Microsoft.VisualStudio.Services.Icons.Default
sources:
  - https://github.com/plantuml/plantuml-server
maintainers:
  - name: stevehipwell
    email: steve.hipwell@gmail.com
